"""initial schema: calls, transcripts, summaries, call_tags, call_tag_overrides, call_events

Revision ID: d0a67f9e8de0
Revises: 
Create Date: 2026-07-12 18:55:55.366899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = 'd0a67f9e8de0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calls_status'), ['status'], unique=False)

    op.create_table('call_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_events_call_id'), ['call_id'], unique=False)

    op.create_table('call_tag_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('tag_category', sa.String(length=50), nullable=False),
    sa.Column('previous_value', sa.String(length=100), nullable=True),
    sa.Column('new_value', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_tag_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_tag_overrides_call_id'), ['call_id'], unique=False)

    op.create_table('call_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('tag_category', sa.String(length=50), nullable=False),
    sa.Column('tag_value', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_tags_call_id'), ['call_id'], unique=False)

    op.create_table('summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('key_points', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('insights', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('llm_provider', sa.String(length=100), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_summaries_call_id'), ['call_id'], unique=True)

    op.create_table('transcripts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('turns', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('stt_provider', sa.String(length=100), nullable=False),
    sa.Column('stt_model', sa.String(length=100), nullable=False),
    sa.Column('stt_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcripts_call_id'), ['call_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcripts_call_id'))

    op.drop_table('transcripts')
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_summaries_call_id'))

    op.drop_table('summaries')
    with op.batch_alter_table('call_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_tags_call_id'))

    op.drop_table('call_tags')
    with op.batch_alter_table('call_tag_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_tag_overrides_call_id'))

    op.drop_table('call_tag_overrides')
    with op.batch_alter_table('call_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_events_call_id'))

    op.drop_table('call_events')
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calls_status'))

    op.drop_table('calls')
    # ### end Alembic commands ###
